options(stringsAsFactors=FALSE,warn=1)
.libPaths(c("__WGPE_R_LIBRARY__",.libPaths()))
suppressPackageStartupMessages(library(ncdf4))
ROOT<-"__WGPE_PROJECT_ROOT__"
src<-file.path(ROOT,"output_TOP100_revision","derived_data","ERA5_TOP100","global_wgpe_1deg_surface_truncated_100hPa_TOP100.RData")
out<-file.path(ROOT,"output_TOP100_revision","results","JRA55","ERA5_TOP100_WGPE_1deg_1982_2023.nc")
e<-new.env();load(src,envir=e)
keep<-e$all_dates>=as.Date("1982-01-01")&e$all_dates<=as.Date("2023-12-01")
stopifnot(sum(keep)==504,identical(dim(e$zbar_st),c(360L,181L,552L)))
dlon<-ncdim_def("lon","degrees_east",as.numeric(e$lon))
dlat<-ncdim_def("lat","degrees_north",as.numeric(e$lat))
dtime<-ncdim_def("time","days since 1982-01-01",as.numeric(e$all_dates[keep]-as.Date("1982-01-01")),unlim=FALSE,calendar="standard")
defs<-lapply(list(iwv=c("kg m-2","integrated water vapour"),zbar=c("m","water-vapour mass-weighted height"),wgpe=c("J m-2","water-vapour gravitational potential energy")),function(x)ncvar_def("placeholder",x[1],list(dlon,dlat,dtime),missval=9.96921e36,prec="float",compression=4,longname=x[2]))
names(defs)<-c("iwv","zbar","wgpe");for(n in names(defs))defs[[n]]$name<-n
nc<-nc_create(out,defs,force_v4=TRUE)
ncvar_put(nc,"iwv",e$iwv_st[,,keep,drop=FALSE]);ncvar_put(nc,"zbar",e$zbar_st[,,keep,drop=FALSE]);ncvar_put(nc,"wgpe",e$wgpe_st[,,keep,drop=FALSE])
ncatt_put(nc,0,"source",src);ncatt_put(nc,0,"vertical_domain","100 hPa to min(local surface pressure, 1000 hPa)")
nc_close(nc)
cat(out,"\n")
